// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdtutrgucqfhzxoyzsci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkdHV0cmd1Y3FmaHp4b3l6c2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTUwNDEsImV4cCI6MjA3MTYzMTA0MX0.GVQgel7Ruk7j2wualyDs5ibR1OQF6McbSKntEsFDe7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});